# version: '3'

# services:
#    python:
#     volumes:
#       - ./Project:/usr/src/Project
#     build:
#       context: ./
#       dockerfile: Dockerfile
#     container_name: python_project

version: '3'
services:
  ai_lerning_containder:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'ai_lerning_containder'
    working_dir: '/usr/src/Project'
    tty: true
    volumes:
      - ./Project:/usr/src/Project